### ISSUE TITLE
Death diss bug?

### ISSUE THREAD

**Issue by shendlaw** [KHKKhalid/SAMPBulletproof#39]
give a look in da screen: http://i.imgur.com/Myed051.png

**Comment by khalidahmedshalabi** [comment]
Well, it looks bad.

**Comment by khalidahmedshalabi** [comment]
Death message to-do:
- Adjust death message box size.
- Bug: both war quotes and death diss messages appear to players who haven't set a death diss message. Needs investigation.
- Bug: new death diss messages are being written on old ones (NO_DEATH_MESSAGE). It's supposed to erase old death diss message then set new one. Needs investigation.
- Bug: we shouldn't show a death-diss for players who die while not in round (e.g in dm or in duel) because it's quite annoying.
